### ISSUE TITLE
메인페이지 HTML & CSS 작성

### ISSUE THREAD

**Issue by j2seon** [5jwon/DourBest#10]
## WHO?
> ALL

## 분류
> 메인페이지

## 설명
> 메인페이지 개발

## TODO
- [x] 슬라이드 
- [x] 인기 순위 section
- [x] 배너
- [x] 오픈 펀딩 section
- [x] 마감 펀딩 section

## Addtional
> 추가적인 내용이 있다면 적어주세요
