### ISSUE TITLE
펀딩 신청 카테고리 선택

### ISSUE THREAD

**Issue by wlgh0702** [5jwon/DourBest#14]
## WHO?
> 판매자

## 분류
> 카테고리 선택 페이지

## 설명
> 카테고리 선택 후 펀딩 신청 버튼 만들기

## TODO
- [x] 닉네임 포함 문구
- [x] 카테고리 선택 옵션 만들기
- [x] 펀딩 신청 버튼 만들기

## Addtional
> 어려워용
