### ISSUE TITLE
메인 HTML & CSS 기본 설정

### ISSUE THREAD

**Issue by j2seon** [5jwon/DourBest#9]
## WHO?
> ALL

## 분류
> 기본설정

## 설명
> 메인페이지 html 및 css 파일 작성

## TODO
- [ ] 메인 HTML 작성
- [ ] default css 작성
- [ ] 헤더 메인 메뉴 작성
- [ ] 헤더 서브 메뉴 작성

## Addtional
> 반응형 미 반영...ㅎ...
